export interface DepartmentItem {
  id: string;
  name: string;
  cities: string[];
}

export const COLOMBIA_DEPARTMENTS: DepartmentItem[] = [
  {
    id: 'bogota',
    name: 'Bogotá D.C.',
    cities: [
      'Bogotá D.C.',
      'Usaquén',
      'Chapinero',
      'Santa Fe',
      'San Cristóbal',
      'Usme',
      'Tunjuelito',
      'Bosa',
      'Kennedy',
      'Fontibón',
      'Engativá',
      'Suba',
      'Barrios Unidos',
      'Teusaquillo',
      'Los Mártires',
      'Antonio Nariño',
      'Puente Aranda',
      'La Candelaria',
      'Rafael Uribe Uribe',
      'Ciudad Bolívar',
      'Sumapaz',
    ],
  },
  {
    id: 'antioquia',
    name: 'Antioquia',
    cities: [
      'Medellín',
      'Bello',
      'Itagüí',
      'Envigado',
      'Apartadó',
      'Rionegro',
      'Turbo',
      'Caucasia',
      'Sabaneta',
      'Caldas',
      'Copacabana',
      'La Estrella',
      'Girardota',
      'Marinilla',
      'Guarne',
      'Santa Rosa de Osos',
      'Yarumal',
      'El Carmen de Viboral',
      'Segovia',
      'Remedios',
      'Chigorodó',
      'Carepa',
      'Sonsón',
      'Amagá',
      'Urrao',
      'Andes',
      'Necoclí',
      'El Bagre',
    ],
  },
  {
    id: 'valle',
    name: 'Valle del Cauca',
    cities: [
      'Cali',
      'Buenaventura',
      'Palmira',
      'Tuluá',
      'Yumbo',
      'Cartago',
      'Jamundí',
      'Buga (Guadalajara de Buga)',
      'Candelaria',
      'Florida',
      'Pradera',
      'Sevilla',
      'Zarzal',
      'Roldanillo',
      'Caicedonia',
      'Bugalagrande',
      'Ginebra',
      'Dagua',
      'Guacarí',
      'La Unión',
    ],
  },
  {
    id: 'cundinamarca',
    name: 'Cundinamarca',
    cities: [
      'Soacha',
      'Chía',
      'Zipaquirá',
      'Facatativá',
      'Fusagasugá',
      'Mosquera',
      'Madrid',
      'Funza',
      'Girardot',
      'Cajicá',
      'Cota',
      'Tocancipá',
      'Sopó',
      'Tabio',
      'Tenjo',
      'La Calera',
      'Ubaté',
      'Villeta',
      'Silvania',
      'Gachancipá',
      'Pacho',
      'Guaduas',
      'La Mesa',
      'Sibate',
      'Anapoima',
    ],
  },
  {
    id: 'atlantico',
    name: 'Atlántico',
    cities: [
      'Barranquilla',
      'Soledad',
      'Malambo',
      'Sabanalarga',
      'Puerto Colombia',
      'Baranoa',
      'Galapa',
      'Santo Tomás',
      'Palmar de Varela',
      'Sabanagrande',
      'Luruaco',
      'Repelón',
      'Polonuevo',
      'Ponedera',
    ],
  },
  {
    id: 'santander',
    name: 'Santander',
    cities: [
      'Bucaramanga',
      'Floridablanca',
      'Girón',
      'Piedecuesta',
      'Barrancabermeja',
      'San Gil',
      'Socorro',
      'Barbosa',
      'Málaga',
      'Lebrija',
      'Cimitarra',
      'Charalá',
      'Vélez',
      'Zapatoca',
      'Rionegro',
      'Sabana de Torres',
      'San Vicente de Chucurí',
    ],
  },
  {
    id: 'bolivar',
    name: 'Bolívar',
    cities: [
      'Cartagena de Indias',
      'Magangué',
      'Turbaco',
      'Arjona',
      'El Carmen de Bolívar',
      'Mompox',
      'San Juan Nepomuceno',
      'Turbana',
      'Calamar',
      'Mahates',
      'San Jacinto',
      'Santa Rosa del Sur',
      'Simití',
      'María La Baja',
    ],
  },
  {
    id: 'norte_santander',
    name: 'Norte de Santander',
    cities: [
      'Cúcuta',
      'Ocaña',
      'Villa del Rosario',
      'Los Patios',
      'Pamplona',
      'Tibú',
      'El Zulia',
      'Chinácota',
      'Ábrego',
      'Sardinata',
      'Toledo',
      'El Tarra',
    ],
  },
  {
    id: 'tolima',
    name: 'Tolima',
    cities: [
      'Ibagué',
      'Espinal',
      'Melgar',
      'Chaparral',
      'Líbano',
      'Mariquita',
      'Honda',
      'Flandes',
      'Guamo',
      'Fresno',
      'Purificación',
      'Armero Guayabal',
      'Cajamarca',
      'Saldaña',
      'Rovira',
    ],
  },
  {
    id: 'huila',
    name: 'Huila',
    cities: [
      'Neiva',
      'Pitalito',
      'Garzón',
      'La Plata',
      'Campoalegre',
      'Palermo',
      'San Agustín',
      'Aipe',
      'Gigante',
      'Algeciras',
      'Rivera',
      'Acevedo',
      'Isnos',
    ],
  },
  {
    id: 'risaralda',
    name: 'Risaralda',
    cities: [
      'Pereira',
      'Dosquebradas',
      'Santa Rosa de Cabal',
      'La Virginia',
      'Belén de Umbría',
      'Quinchía',
      'Santuario',
      'Marsella',
      'Guática',
      'Apía',
    ],
  },
  {
    id: 'caldas',
    name: 'Caldas',
    cities: [
      'Manizales',
      'La Dorada',
      'Chinchiná',
      'Villamaría',
      'Riosucio',
      'Anserma',
      'Salamina',
      'Aguadas',
      'Neira',
      'Supía',
      'Pensilvania',
      'Viterbo',
    ],
  },
  {
    id: 'quindio',
    name: 'Quindío',
    cities: [
      'Armenia',
      'Calarcá',
      'La Tebaida',
      'Montenegro',
      'Quimbaya',
      'Circasia',
      'Filandia',
      'Salento',
      'Génova',
      'Pijao',
    ],
  },
  {
    id: 'boyaca',
    name: 'Boyacá',
    cities: [
      'Tunja',
      'Duitama',
      'Sogamoso',
      'Chiquinquirá',
      'Paipa',
      'Puerto Boyacá',
      'Villa de Leyva',
      'Moniquirá',
      'Nobsa',
      'Samacá',
      'Garagoa',
      'Tibasosa',
      'Soatá',
      'Ventaquemada',
    ],
  },
  {
    id: 'meta',
    name: 'Meta',
    cities: [
      'Villavicencio',
      'Acacías',
      'Granada',
      'Puerto López',
      'San Martín',
      'Cumaral',
      'Puerto Gaitán',
      'Guamal',
      'Restrepo',
      'Castilla La Nueva',
    ],
  },
  {
    id: 'narino',
    name: 'Nariño',
    cities: [
      'Pasto',
      'Tumaco',
      'Ipiales',
      'Túquerres',
      'La Unión',
      'Sandoná',
      'Samaniego',
      'Cumbal',
      'Buesaco',
      'El Charco',
    ],
  },
  {
    id: 'cauca',
    name: 'Cauca',
    cities: [
      'Popayán',
      'Santander de Quilichao',
      'Puerto Tejada',
      'Patía (El Bordo)',
      'Piendamó',
      'Bolívar',
      'Corinto',
      'Miranda',
      'Silvia',
      'Guapi',
    ],
  },
  {
    id: 'cesar',
    name: 'Cesar',
    cities: [
      'Valledupar',
      'Aguachica',
      'Agustín Codazzi',
      'Bosconia',
      'Curumaní',
      'El Copey',
      'La Paz',
      'San Alberto',
      'Chiriguaná',
      'La Jagua de Ibirico',
    ],
  },
  {
    id: 'cordoba',
    name: 'Córdoba',
    cities: [
      'Montería',
      'Cereté',
      'Sahagún',
      'Lorica',
      'Montelíbano',
      'Planeta Rica',
      'Tierralta',
      'Ciénaga de Oro',
      'Chinú',
      'San Antero',
      'Ayapel',
    ],
  },
  {
    id: 'magdalena',
    name: 'Magdalena',
    cities: [
      'Santa Marta',
      'Ciénaga',
      'Fundación',
      'El Banco',
      'Plato',
      'Aracataca',
      'Pivijay',
      'Zona Bananera',
      'El Retén',
      'Sitio Nuevo',
    ],
  },
  {
    id: 'sucre',
    name: 'Sucre',
    cities: [
      'Sincelejo',
      'Corozal',
      'San Marcos',
      'San Onofre',
      'Santiago de Tolú',
      'Sampués',
      'Toluviejo',
      'San Pedro',
      'Majagual',
      'Coveñas',
    ],
  },
  {
    id: 'la_guajira',
    name: 'La Guajira',
    cities: [
      'Riohacha',
      'Maicao',
      'Uribia',
      'Manaure',
      'Fonseca',
      'San Juan del Cesar',
      'Villanueva',
      'Hatonuevo',
      'Dibulla',
      'Barrancas',
    ],
  },
  {
    id: 'casanare',
    name: 'Casanare',
    cities: [
      'Yopal',
      'Aguazul',
      'Villanueva',
      'Tauramena',
      'Paz de Ariporo',
      'Monterrey',
      'Maní',
      'Hato Corozal',
      'Trinidad',
    ],
  },
  {
    id: 'caqueta',
    name: 'Caquetá',
    cities: [
      'Florencia',
      'San Vicente del Caguán',
      'Cartagena del Chairá',
      'Puerto Rico',
      'El Doncello',
      'Belén de los Andaquíes',
    ],
  },
  {
    id: 'putumayo',
    name: 'Putumayo',
    cities: [
      'Mocoa',
      'Puerto Asís',
      'Orito',
      'Valle del Guamuez (La Hormiga)',
      'Villagarzón',
      'Sibundoy',
      'San Miguel',
    ],
  },
  {
    id: 'choco',
    name: 'Chocó',
    cities: [
      'Quibdó',
      'Istmina',
      'Condoto',
      'Tadó',
      'Bahía Solano',
      'Acandí',
      'Nuquí',
      'Riosucio',
    ],
  },
  {
    id: 'arauca',
    name: 'Arauca',
    cities: [
      'Arauca',
      'Tame',
      'Saravena',
      'Arauquita',
      'Fortul',
      'Cravo Norte',
    ],
  },
  {
    id: 'san_andres',
    name: 'San Andrés y Providencia',
    cities: [
      'San Andrés',
      'Providencia',
    ],
  },
  {
    id: 'amazonas',
    name: 'Amazonas',
    cities: [
      'Leticia',
      'Puerto Nariño',
    ],
  },
  {
    id: 'guaviare',
    name: 'Guaviare',
    cities: [
      'San José del Guaviare',
      'El Retorno',
      'Calamar',
      'Miraflores',
    ],
  },
  {
    id: 'guainia',
    name: 'Guainía',
    cities: [
      'Inírida',
      'Barranco Minas',
    ],
  },
  {
    id: 'vaupes',
    name: 'Vaupés',
    cities: [
      'Mitú',
      'Carurú',
      'Taraira',
    ],
  },
  {
    id: 'vichada',
    name: 'Vichada',
    cities: [
      'Puerto Carreño',
      'La Primavera',
      'Santa Rosalía',
      'Cumaribo',
    ],
  },
];
